name = "pog"
version = "1.0.0"
gleam = ">= 1.4.0"
licences = ["Apache-2.0"]
description = "A PostgreSQL database client for Gleam, based on PGO"

repository = { type = "github", user = "lpil", repo = "pog" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.20.0 and < 2.0.0"
pgo = ">= 0.12.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
exception = ">= 2.0.0 and < 3.0.0"

[erlang]
# Starting an SSL connection relies on ssl application to be started.
extra_applications = ["ssl"]
