name = "gleam_pgo"
version = "0.12.0"
gleam = ">= 0.32.0"
licences = ["Apache-2.0"]
description = "Gleam bindings to the PGO PostgreSQL client"

repository = { type = "github", user = "gleam-experiments", repo = "pgo" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.20.0 and < 2.0.0"
pgo = ">= 0.12.0 and < 2.0.0"

[dev-dependencies]
gleeunit = "~> 1.0"
exception = ">= 2.0.0 and < 3.0.0"
